# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-06 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_auto_20180406_0522'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewstatus',
            options={'ordering': ['order', 'name', 'code']},
        ),
        migrations.AlterField(
            model_name='reviewstatus',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='reviewstatus',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
