# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-07 12:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_auto_20180406_1945'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewStatus',
        ),
    ]
