# Generated by Django 2.2.13 on 2020-07-13 15:18

import apps.project.models
from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0041_auto_20200522_0811'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='project',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
                ('objects', apps.project.models.ProjectManager()),
            ],
        ),
    ]
