/*
 * Contraxsuite API
 *
 * Contraxsuite API
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// DocumentSetAnnotatorCoordinatesDifferenceRequestFirstLettersInner
    /// </summary>
    [DataContract]
    public partial class DocumentSetAnnotatorCoordinatesDifferenceRequestFirstLettersInner :  IEquatable<DocumentSetAnnotatorCoordinatesDifferenceRequestFirstLettersInner>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DocumentSetAnnotatorCoordinatesDifferenceRequestFirstLettersInner" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected DocumentSetAnnotatorCoordinatesDifferenceRequestFirstLettersInner() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="DocumentSetAnnotatorCoordinatesDifferenceRequestFirstLettersInner" /> class.
        /// </summary>
        /// <param name="x">x (required).</param>
        /// <param name="y">y (required).</param>
        /// <param name="letter">letter (required).</param>
        public DocumentSetAnnotatorCoordinatesDifferenceRequestFirstLettersInner(decimal x = default(decimal), decimal y = default(decimal), string letter = default(string))
        {
            // to ensure "x" is required (not null)
            if (x == null)
            {
                throw new InvalidDataException("x is a required property for DocumentSetAnnotatorCoordinatesDifferenceRequestFirstLettersInner and cannot be null");
            }
            else
            {
                this.X = x;
            }

            // to ensure "y" is required (not null)
            if (y == null)
            {
                throw new InvalidDataException("y is a required property for DocumentSetAnnotatorCoordinatesDifferenceRequestFirstLettersInner and cannot be null");
            }
            else
            {
                this.Y = y;
            }

            // to ensure "letter" is required (not null)
            if (letter == null)
            {
                throw new InvalidDataException("letter is a required property for DocumentSetAnnotatorCoordinatesDifferenceRequestFirstLettersInner and cannot be null");
            }
            else
            {
                this.Letter = letter;
            }

        }

        /// <summary>
        /// Gets or Sets X
        /// </summary>
        [DataMember(Name="x", EmitDefaultValue=true)]
        public decimal X { get; set; }

        /// <summary>
        /// Gets or Sets Y
        /// </summary>
        [DataMember(Name="y", EmitDefaultValue=true)]
        public decimal Y { get; set; }

        /// <summary>
        /// Gets or Sets Letter
        /// </summary>
        [DataMember(Name="letter", EmitDefaultValue=true)]
        public string Letter { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DocumentSetAnnotatorCoordinatesDifferenceRequestFirstLettersInner {\n");
            sb.Append("  X: ").Append(X).Append("\n");
            sb.Append("  Y: ").Append(Y).Append("\n");
            sb.Append("  Letter: ").Append(Letter).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as DocumentSetAnnotatorCoordinatesDifferenceRequestFirstLettersInner);
        }

        /// <summary>
        /// Returns true if DocumentSetAnnotatorCoordinatesDifferenceRequestFirstLettersInner instances are equal
        /// </summary>
        /// <param name="input">Instance of DocumentSetAnnotatorCoordinatesDifferenceRequestFirstLettersInner to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DocumentSetAnnotatorCoordinatesDifferenceRequestFirstLettersInner input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.X == input.X ||
                    (this.X != null &&
                    this.X.Equals(input.X))
                ) && 
                (
                    this.Y == input.Y ||
                    (this.Y != null &&
                    this.Y.Equals(input.Y))
                ) && 
                (
                    this.Letter == input.Letter ||
                    (this.Letter != null &&
                    this.Letter.Equals(input.Letter))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.X != null)
                    hashCode = hashCode * 59 + this.X.GetHashCode();
                if (this.Y != null)
                    hashCode = hashCode * 59 + this.Y.GetHashCode();
                if (this.Letter != null)
                    hashCode = hashCode * 59 + this.Letter.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
