# Generated by Django 2.2.13 on 2020-07-13 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materialized_views', '0002_materializedview_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materializedview',
            name='last_update_duration',
        ),
    ]
