/*
 * Contraxsuite API
 *
 * Contraxsuite API
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing Action
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ActionTests
    {
        // TODO uncomment below to declare an instance variable for Action
        //private Action instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Action
            //instance = new Action();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Action
        /// </summary>
        [Test]
        public void ActionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" Action
            //Assert.IsInstanceOf(typeof(Action), instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Test]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
        /// <summary>
        /// Test the property 'ViewAction'
        /// </summary>
        [Test]
        public void ViewActionTest()
        {
            // TODO unit test for the property 'ViewAction'
        }
        /// <summary>
        /// Test the property 'ObjectPk'
        /// </summary>
        [Test]
        public void ObjectPkTest()
        {
            // TODO unit test for the property 'ObjectPk'
        }
        /// <summary>
        /// Test the property 'ModelName'
        /// </summary>
        [Test]
        public void ModelNameTest()
        {
            // TODO unit test for the property 'ModelName'
        }
        /// <summary>
        /// Test the property 'Date'
        /// </summary>
        [Test]
        public void DateTest()
        {
            // TODO unit test for the property 'Date'
        }
        /// <summary>
        /// Test the property 'UserName'
        /// </summary>
        [Test]
        public void UserNameTest()
        {
            // TODO unit test for the property 'UserName'
        }
        /// <summary>
        /// Test the property 'RequestData'
        /// </summary>
        [Test]
        public void RequestDataTest()
        {
            // TODO unit test for the property 'RequestData'
        }

    }

}
