/*
 * Contraxsuite API
 *
 * Contraxsuite API
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing MarkForSeenWebNotificationRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MarkForSeenWebNotificationRequestTests
    {
        // TODO uncomment below to declare an instance variable for MarkForSeenWebNotificationRequest
        //private MarkForSeenWebNotificationRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MarkForSeenWebNotificationRequest
            //instance = new MarkForSeenWebNotificationRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MarkForSeenWebNotificationRequest
        /// </summary>
        [Test]
        public void MarkForSeenWebNotificationRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" MarkForSeenWebNotificationRequest
            //Assert.IsInstanceOf(typeof(MarkForSeenWebNotificationRequest), instance);
        }


        /// <summary>
        /// Test the property 'NotificationIds'
        /// </summary>
        [Test]
        public void NotificationIdsTest()
        {
            // TODO unit test for the property 'NotificationIds'
        }
        /// <summary>
        /// Test the property 'IsSeen'
        /// </summary>
        [Test]
        public void IsSeenTest()
        {
            // TODO unit test for the property 'IsSeen'
        }

    }

}
