/*
 * Contraxsuite API
 *
 * Contraxsuite API
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing UploadSessionCreate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UploadSessionCreateTests
    {
        // TODO uncomment below to declare an instance variable for UploadSessionCreate
        //private UploadSessionCreate instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UploadSessionCreate
            //instance = new UploadSessionCreate();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UploadSessionCreate
        /// </summary>
        [Test]
        public void UploadSessionCreateInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" UploadSessionCreate
            //Assert.IsInstanceOf(typeof(UploadSessionCreate), instance);
        }


        /// <summary>
        /// Test the property 'Uid'
        /// </summary>
        [Test]
        public void UidTest()
        {
            // TODO unit test for the property 'Uid'
        }
        /// <summary>
        /// Test the property 'Project'
        /// </summary>
        [Test]
        public void ProjectTest()
        {
            // TODO unit test for the property 'Project'
        }
        /// <summary>
        /// Test the property 'CreatedBy'
        /// </summary>
        [Test]
        public void CreatedByTest()
        {
            // TODO unit test for the property 'CreatedBy'
        }
        /// <summary>
        /// Test the property 'UploadFiles'
        /// </summary>
        [Test]
        public void UploadFilesTest()
        {
            // TODO unit test for the property 'UploadFiles'
        }
        /// <summary>
        /// Test the property 'ReviewFiles'
        /// </summary>
        [Test]
        public void ReviewFilesTest()
        {
            // TODO unit test for the property 'ReviewFiles'
        }
        /// <summary>
        /// Test the property 'Force'
        /// </summary>
        [Test]
        public void ForceTest()
        {
            // TODO unit test for the property 'Force'
        }

    }

}
