# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-27 17:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_effective_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='title',
        ),
    ]
