# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-07 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_auto_20171106_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provision',
            name='text_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.TextUnit'),
        ),
    ]
