---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  labels:
    service: rabbitmq-service
spec:
  type: ClusterIP
  ports:
    - name: epmd
      port: 4369
      targetPort: epmd
    - name: amqp
      port: 5672
      targetPort: amqp
    - name: dist
      port: 25672
      targetPort: dist
    - name: stats
      port: 15672
      targetPort: stats
  selector:
    app: contrax-rabbitmq
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: contrax-rabbitmq
  deletionGracePeriodSeconds: 120
  labels:
    app: contrax-rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contrax-rabbitmq
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: contrax-rabbitmq
    spec:
      hostname: contrax-rabbitmq
      volumes:
        - name: rabbitmq-data
          persistentVolumeClaim:
            claimName: rabbitmq-storage
      containers:
        - image: "rabbitmq:3-management"
          name: contrax-rabbitmq
          volumeMounts:
            - name: rabbitmq-data
              mountPath: "/var/lib/rabbitmq"
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: "admin"
            - name: RABBITMQ_DEFAULT_PASS
              value: "admin"
            - name: RABBITMQ_DEFAULT_VHOST
              value: "rabbitmq-service"
          ports:
            - name: epmd
              containerPort: 4369
            - name: amqp
              containerPort: 5672
            - name: dist
              containerPort: 25672
            - name: stats
              containerPort: 15672