#---
#apiVersion: apps/v1beta1
#kind: Deployment
#metadata:
#  name: contrax-flower
#  deletionGracePeriodSeconds: 120
#  labels:
#    app: contrax-flower
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      app: contrax-flower
#  strategy:
#    type: RollingUpdate
#  template:
#    metadata:
#      labels:
#        app: contrax-flower
#    spec:
#      hostname: contrax-flower
#      volumes:
#        - name: contraxsuite-deployment-uuid
#          persistentVolumeClaim:
#            claimName: lexpredict-storage
#        - name: contraxsuite-nginx-certs
#          persistentVolumeClaim:
#            claimName: lexpredict-storage
#        - name: contraxsuite-data-media
#          persistentVolumeClaim:
#            claimName: lexpredict-storage
#        - name: contraxsuite-static-files
#          persistentVolumeClaim:
#            claimName: lexpredict-storage
#        - name: contraxsuite-third-party-dependencies
#          persistentVolumeClaim:
#            claimName: lexpredict-storage
#        - name: contraxsuite-logs
#          persistentVolumeClaim:
#            claimName: lexpredict-storage
#        - name: contraxsuite-internal-nginx-logs
#          persistentVolumeClaim:
#            claimName: lexpredict-storage
#        - name: contraxsuite-notebooks
#          persistentVolumeClaim:
#            claimName: lexpredict-storage
#        - name: helper-script
#          configMap:
#            name: init-config
#      initContainers:
#        - name: helper
#          image: "alpine:latest"
#          command:
#            - "sh"
#            - "/init.sh"
#          volumeMounts:
#            - name: helper-script
#              mountPath: "/init.sh"
#              subPath: "init.sh"
#            - name: contraxsuite-third-party-dependencies
#              mountPath: "/third_party_dependencies"
#      containers:
#        - image: "lexpredict/lexpredict-contraxsuite:{{.Values.lexpredict.version}}"
#          name: contrax-flower
#          ports:
#          - name: "flower"
#            containerPort: 5555
#          command:
#            - "/start.sh"
#            - "flower"
#          env:
#            - name: SHARED_USER_NAME
#              value: "contrax"
#            - name: SHARED_USER_ID
#              value: "65432"
#            - name: DOCKER_HOST_NAME_PG
#              value: "postgres-service"
#            - name: DOCKER_HOST_NAME_REDIS
#              value: "contrax-redis-service"
#            - name: DOCKER_HOST_NAME_RABBITMQ
#              value: "rabbitmq-service"
#            - name: DOCKER_HOST_NAME_ELASTICSEARCH
#              value: "contrax-elasticsearch-service"
#            - name: DOCKER_HOST_NAME_UWSGI
#              value: "contrax-uwsgi-service"
#            - name: DOCKER_HOST_NAME_KIBANA
#              value: "contrax-kibana-service"
#            - name: DOCKER_PG_USER
#              value: "admin"
#            - name: DOCKER_PG_PASSWORD
#              value: "admin"
#            - name: DOCKER_PG_DB_NAME
#              value: "contrax"
#            - name: DOCKER_RABBITMQ_VHOST
#              value: "rabbitmq-service"
#            - name: DOCKER_RABBITMQ_USER
#              value: "admin"
#            - name: DOCKER_RABBITMQ_PASSWORD
#              value: "admin"
#            - name: DOCKER_DJANGO_HOST_NAME
#              value: "localhost"
#            - name: DOCKER_DJANGO_EMAIL_BACKEND
#              value: "django.core.mail.backends.console.EmailBackend"
#            - name: DOCKER_DJANGO_EMAIL_HOST
#              value: "localhost"
#            - name: DOCKER_DJANGO_EMAIL_PORT
#              value: "587"
#            - name: DOCKER_DJANGO_EMAIL_USE_TLS
#              value: "False"
#            - name: DOCKER_DJANGO_EMAIL_HOST_USER
#              value: "admin"
#            - name: DOCKER_DJANGO_EMAIL_HOST_PASSWORD
#              value: "admin"
#            - name: DOCKER_DJANGO_ADMIN_NAME
#              value: "admin"
#            - name: DOCKER_DJANGO_ADMIN_PASSWORD
#              value: "admin"
#            - name: DOCKER_DJANGO_ADMIN_EMAIL
#              value: "admin@rc.com"
#            - name: DOCKER_DJANGO_DEBUG
#              value: "True"
#            - name: DOCKER_DJANGO_DEBUG_SQL
#              value: "True"
#            - name: DOCKER_DJANGO_SECRET_KEY
#              value: "verysecretkey"
#            - name: DOCKER_DJANGO_ACCOUNT_EMAIL_VERIFICATION
#              value: "optional"
#            - name: DOCKER_JUPYTER_BASE_URL
#              value: "/jupyter"
#            - name: DOCKER_NGINX_SERVER_NAME
#              value: "contrax-nginx"
#            - name: DOCKER_JUPYTER_PORT
#              value: "8888"
#            - name: DOCKER_DJANGO_BASE_PATH
#              value: "/"
#            - name: DOCKER_FLOWER_BASE_PATH
#              value: "flower"
#          volumeMounts:
#            - name: contraxsuite-deployment-uuid
#              mountPath: "/deployment_uuid"
#            - name: contraxsuite-nginx-certs
#              mountPath: "/etc/nginx/certificates"
#            - name: contraxsuite-data-media
#              mountPath: "/data/media"
#            - name: contraxsuite-static-files
#              mountPath: "/contraxsuite_services/staticfiles"
#            - name: contraxsuite-third-party-dependencies
#              mountPath: "/third_party_dependencies"
#            - name: contraxsuite-logs
#              mountPath: "/data/logs"
#            - name: contraxsuite-internal-nginx-logs
#              mountPath: "/var/log/nginx"
#            - name: contraxsuite-notebooks
#              mountPath: "/contraxsuite_services/notebooks"
---
apiVersion: v1
kind: Service
metadata:
  name: contrax-flower-service
  labels:
    service: contrax-flower-service
spec:
  type: ClusterIP
  ports:
    - name: flower
      port: 5555
      targetPort: flower
  selector:
    app: contrax-flower