---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "logrotate-config"
data:
  logrotate.conf: |
    /logs/nginx/*.log {
        daily
        rotate 5
        compress
        copytruncate
        missingok
        su root root
    }

    /logs/contraxsuite/*.log
    /logs/contraxsuite/*.log_json {
        daily
        rotate 5
        compress
        missingok
        su root root
    }

  root: |
    # min	hour	day	month	weekday	command

    */15 *	* * *	/usr/sbin/logrotate -s /logrotate/status /etc/logrotate.conf
    */15 *	* * *	find /logs/contraxsuite -type f -mtime +5 -name '*.log*.gz' -print0 | xargs -r0 rm --
    */15 *	* * *	find /logs/pg_data/pg_log -type f -mtime +3 -name '*.log*' -print0 | xargs -r0 rm --


#---
#apiVersion: apps/v1beta1
#kind: Deployment
#metadata:
#  name: contrax-logrotate
#  deletionGracePeriodSeconds: 120
#  labels:
#    app: contrax-logrotate
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      app: contrax-logrotate
#  strategy:
#    type: RollingUpdate
#  template:
#    metadata:
#      labels:
#        app: contrax-logrotate
#    spec:
#      hostname: contrax-logrotate
#      volumes:
#        - name: contraxsuite-internal-nginx-logs
#          persistentVolumeClaim:
#            claimName: lexpredict-storage
#        - name: contraxsuite-logs
#          persistentVolumeClaim:
#            claimName: lexpredict-storage
#        - name: postgres-data
#          persistentVolumeClaim:
#            claimName: lexpredict-storage
#        - name: contraxsuite-logrotate
#          emptyDir: {}
#        - name: logrotate-config
#          configMap:
#            name: "logrotate-config"
#      containers:
#        - image: "tutum/logrotate:latest"
#          name: contrax-logrotate
#          volumeMounts:
#            - name: contraxsuite-internal-nginx-logs
#              mountPath: "/logs/nginx"
#            - name: contraxsuite-logs
#              mountPath: "/logs/contraxsuite"
#            - name: postgres-data
#              mountPath: "/logs/pg_data"
#            - name: contraxsuite-logrotate
#              mountPath: "/logrotate"
#            - name: logrotate-config
#              mountPath: "/etc/logrotate.conf"
#              subPath: "logrotate.conf"
#            - name: logrotate-config
#              mountPath: "/etc/crontabs/root"
#              subPath: "root"