---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: contrax-kibana
  deletionGracePeriodSeconds: 120
  labels:
    app: "contrax-kibana"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "contrax-kibana"
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: "contrax-kibana"
    spec:
      hostname: contrax-kibana
      containers:
        - name: contrax-kibana
          image: "docker.elastic.co/kibana/kibana-oss:6.5.4"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5601
              name: kibana-port
          env:
            - name: "ELASTICSEARCH_URL"
              value: "http://contrax-elasticsearch-service:9200"
---
apiVersion: v1
kind: Service
metadata:
  name: "contrax-kibana-service"
  labels:
    service: "contrax-kibana-service"
spec:
  selector:
    app: "contrax-kibana"
  ports:
    - port: 5601
      targetPort: kibana-port