# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-07 08:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rawdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttypecachingconfig',
            name='document_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='caching_config', to='document.DocumentType'),
        ),
    ]
