# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-19 09:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('document', '0111_documentfielddetector_text_part'),
        ('project', '0029_auto_20181102_1910'),
        ('rawdb', '0003_auto_20181211_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('document_sort_order', models.CharField(max_length=1024)),
                ('filter_sql', models.TextField(blank=True, null=True)),
                ('filter_query', models.TextField(blank=True, null=True)),
                ('order_by', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('document_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='document.DocumentType')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
            ],
        ),
    ]
