# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-19 13:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rawdb', '0005_remove_savedfilter_document_sort_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedfilter',
            name='filter_sql',
        ),
    ]
