# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-01-04 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawdb', '0013_add_app_vars_descriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedfilter',
            name='filter_type',
            field=models.CharField(choices=[('common_filter', 'Common Filter'), ('user_doc_grid_config', 'User Document Grid Config')], default='common_filter', max_length=50),
        ),
    ]
