/*
 * Contraxsuite API
 * Contraxsuite API
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * SelectProjectsResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-06-16T11:43:26.677726+03:00[Europe/Moscow]")
public class SelectProjectsResponse {
  public static final String SERIALIZED_NAME_SAVED_FILTER_ID = "saved_filter_id";
  @SerializedName(SERIALIZED_NAME_SAVED_FILTER_ID)
  private Integer savedFilterId;

  public static final String SERIALIZED_NAME_USER_ID = "user_id";
  @SerializedName(SERIALIZED_NAME_USER_ID)
  private Integer userId;

  public static final String SERIALIZED_NAME_PROJECT_IDS = "project_ids";
  @SerializedName(SERIALIZED_NAME_PROJECT_IDS)
  private List<Integer> projectIds = new ArrayList<>();

  public static final String SERIALIZED_NAME_SHOW_WARNING = "show_warning";
  @SerializedName(SERIALIZED_NAME_SHOW_WARNING)
  private Boolean showWarning;

  public SelectProjectsResponse() { 
  }

  public SelectProjectsResponse savedFilterId(Integer savedFilterId) {
    
    this.savedFilterId = savedFilterId;
    return this;
  }

   /**
   * Get savedFilterId
   * @return savedFilterId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Integer getSavedFilterId() {
    return savedFilterId;
  }


  public void setSavedFilterId(Integer savedFilterId) {
    this.savedFilterId = savedFilterId;
  }


  public SelectProjectsResponse userId(Integer userId) {
    
    this.userId = userId;
    return this;
  }

   /**
   * Get userId
   * @return userId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Integer getUserId() {
    return userId;
  }


  public void setUserId(Integer userId) {
    this.userId = userId;
  }


  public SelectProjectsResponse projectIds(List<Integer> projectIds) {
    
    this.projectIds = projectIds;
    return this;
  }

  public SelectProjectsResponse addProjectIdsItem(Integer projectIdsItem) {
    this.projectIds.add(projectIdsItem);
    return this;
  }

   /**
   * Get projectIds
   * @return projectIds
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public List<Integer> getProjectIds() {
    return projectIds;
  }


  public void setProjectIds(List<Integer> projectIds) {
    this.projectIds = projectIds;
  }


  public SelectProjectsResponse showWarning(Boolean showWarning) {
    
    this.showWarning = showWarning;
    return this;
  }

   /**
   * Get showWarning
   * @return showWarning
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Boolean getShowWarning() {
    return showWarning;
  }


  public void setShowWarning(Boolean showWarning) {
    this.showWarning = showWarning;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SelectProjectsResponse selectProjectsResponse = (SelectProjectsResponse) o;
    return Objects.equals(this.savedFilterId, selectProjectsResponse.savedFilterId) &&
        Objects.equals(this.userId, selectProjectsResponse.userId) &&
        Objects.equals(this.projectIds, selectProjectsResponse.projectIds) &&
        Objects.equals(this.showWarning, selectProjectsResponse.showWarning);
  }

  @Override
  public int hashCode() {
    return Objects.hash(savedFilterId, userId, projectIds, showWarning);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SelectProjectsResponse {\n");
    sb.append("    savedFilterId: ").append(toIndentedString(savedFilterId)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    projectIds: ").append(toIndentedString(projectIds)).append("\n");
    sb.append("    showWarning: ").append(toIndentedString(showWarning)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("saved_filter_id");
    openapiFields.add("user_id");
    openapiFields.add("project_ids");
    openapiFields.add("show_warning");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("saved_filter_id");
    openapiRequiredFields.add("user_id");
    openapiRequiredFields.add("project_ids");
    openapiRequiredFields.add("show_warning");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to SelectProjectsResponse
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (SelectProjectsResponse.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in SelectProjectsResponse is not found in the empty JSON string", SelectProjectsResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!SelectProjectsResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `SelectProjectsResponse` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : SelectProjectsResponse.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      // ensure the json data is an array
      if (jsonObj.get("project_ids") != null && !jsonObj.get("project_ids").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `project_ids` to be an array in the JSON string but got `%s`", jsonObj.get("project_ids").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SelectProjectsResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SelectProjectsResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SelectProjectsResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SelectProjectsResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<SelectProjectsResponse>() {
           @Override
           public void write(JsonWriter out, SelectProjectsResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public SelectProjectsResponse read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of SelectProjectsResponse given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of SelectProjectsResponse
  * @throws IOException if the JSON string is invalid with respect to SelectProjectsResponse
  */
  public static SelectProjectsResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SelectProjectsResponse.class);
  }

 /**
  * Convert an instance of SelectProjectsResponse to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

