#!/bin/bash

# Variables that a set on Jenkins build
if [[ -f helm_setenv_local.sh ]]; then
    echo "Loading helm_setenv_local.sh"
    source helm_setenv_local.sh
fi

export DOCKER_DJANGO_HOST_NAME=${CONTRAX_DOMAIN_NAME}
export DOCKER_FRONTEND_ROOT_URL=${CONTRAX_DOMAIN_NAME}

# Rewrite DOCKER_TEXT_EXTRACTION_SYSTEM_URL for K8S
export DOCKER_TEXT_EXTRACTION_SYSTEM_URL=http://${DOCKER_HOST_NAME_TEXT_EXTRACTION_SYSTEM_API}:${DOCKER_TEXT_EXTRACTION_SYSTEM_API_PORT}
export DOCKER_HOST_NAME_PG_ACCESS=contrax-db
export DJANGO_WEBSRV_DB_HOST=${DOCKER_PGBOUNCER_SESS_HOST}
export DJANGO_CELERY_DB_HOST=${DOCKER_PGBOUNCER_TRANS_HOST}
export DOCKER_HOST_NAME_REDIS_ACCESS=contrax-redis
export DOCKER_HOST_NAME_RABBITMQ_ACCESS=contrax-rabbitmq
export DOCKER_HOST_NAME_ELASTICSEARCH_ACCESS=contrax-elasticsearch
export DOCKER_HOST_NAME_DAPHNE_ACCESS=contrax-daphne
export DOCKER_WEBDAV_SERVER_NAME_ACCESS=contrax-webdav
export DOCKER_RABBITMQ_VHOST=${DOCKER_RABBITMQ_VHOST}
export DOCKER_RABBITMQ_USER=${DOCKER_RABBITMQ_USER}
export DOCKER_RABBITMQ_PASSWORD=${DOCKER_RABBITMQ_PASSWORD}


