# Generated by Django 2.2 on 2019-04-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lease', '0017_auto_20171219_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leasedocument',
            name='arbitration_clause',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='leasedocument',
            name='auto_renew',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='leasedocument',
            name='choice_of_law_clause',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='leasedocument',
            name='construction_allowance',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='leasedocument',
            name='forum_selection_clause',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='leasedocument',
            name='mediation_required',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
