# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-22 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('technical_admin', 'technical_admin'), ('manager', 'manager'), ('reviewer', 'reviewer'), ('project_creator', 'project_creator')], default='reviewer', max_length=30, verbose_name='Role'),
        ),
    ]
