# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-26 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180522_0810'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name of Role')),
                ('code', models.CharField(max_length=50, verbose_name='Role Code')),
                ('order', models.PositiveSmallIntegerField()),
                ('is_admin', models.BooleanField(db_index=True, default=False)),
                ('is_manager', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'ordering': ('order', 'name'),
            },
        ),
    ]
