# Generated by Django 2.2.13 on 2020-07-30 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
        ('users', '0014_auto_20200713_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAppUri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri_type', models.CharField(choices=[('auth', 'auth'), ('token', 'token'), ('profile', 'profile')], db_index=True, max_length=64)),
                ('uri', models.CharField(db_index=True, max_length=1024, null=True)),
                ('social_app', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='socialaccount.SocialApp')),
            ],
            options={
                'ordering': ('social_app', 'uri_type'),
                'unique_together': {('social_app', 'uri_type')},
            },
        ),
    ]
