# Generated by Django 2.2.13 on 2020-12-24 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0011_auto_20201224_1533'),
        ('users', '0020_auto_20201218_0759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
