# Generated by Django 2.2.20 on 2021-05-11 08:44

from django.db import migrations, models


def add_initials(apps, schema_editor):
    User = apps.get_model('users', 'User')
    from apps.users.models import User as user_model
    for user in User.objects.all():
        user.initials = user_model._get_initials(user.name)
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_unique_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='initials',
            field=models.CharField(blank=True, max_length=2, verbose_name='User Initials'),
        ),
        migrations.RunPython(add_initials),
    ]
