# Generated by Django 2.2.28 on 2022-06-15 13:02

from django.db import migrations

from apps.users.permissions import permissions_for


def add_app_var_perms(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    appvar_perms_list = [i for i in permissions_for('common', 'appvar')
                         if i['perm_name'].split('_')[0] not in ('add', 'delete')]
    groups_to_change = Group.objects.filter(name__in=['Project and Document Type Creator'])
    for group in groups_to_change:
        for perm in appvar_perms_list:
            try:
                permission = Permission.objects.get(content_type__app_label=perm['app_name'],
                                                    content_type__model=perm['model_name'],
                                                    codename=perm['perm_name'])
                group.permissions.add(permission)
            except:
                # case when permission was added later
                pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_add_task_perms_to_project_and_doc_type_creator_group'),
    ]

    operations = [
        migrations.RunPython(add_app_var_perms, reverse_code=migrations.RunPython.noop),
    ]
