# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-10 11:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_auto_20180404_0851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltask',
            name='log',
        ),
        migrations.RemoveField(
            model_name='task',
            name='log',
        ),
    ]
