# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-06 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0012_auto_20180606_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskconfig',
            name='default_retry_delay',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskconfig',
            name='retry_backoff',
            field=models.BooleanField(default=True),
        ),
    ]
