# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-13 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0015_auto_20180610_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='main_celery_task_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='celery_task_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True, verbose_name='task id'),
        ),
    ]
