# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-24 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0027_auto_20180624_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='failure_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='push_steps',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
