# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-24 22:42
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0028_auto_20180624_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='log_extra',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
