# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-25 14:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0020_fix_projectclustering_task_id_type_20180706_0858'),
        ('task', '0030_create_undex_20180712_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Project'),
        ),
        migrations.AddField(
            model_name='task',
            name='upload_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.UploadSession'),
        ),
    ]
