# Generated by Django 2.2.13 on 2020-11-05 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0065_raise_failure_status_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskStatEntry',
            fields=[
                ('task_name', models.CharField(max_length=256, primary_key=True, serialize=False, unique=True)),
                ('run_counter', models.IntegerField(default=0)),
            ],
        ),
    ]
