# Generated by Django 2.2.13 on 2020-12-03 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0066_taskstatentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='bad_health_check_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
