# Generated by Django 2.2.13 on 2021-04-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0072_auto_20210402_1120'),
    ]

    operations = [
        migrations.RunSQL(
            '''update task_task set "display_name" = 'Retrain Rough Fields' where "display_name" = 'Retrain Dirty Fields'; '''
        ),
        migrations.RunSQL(
            '''update task_task set "display_name" = 'Train Rough Document Field Detector Model' where "display_name" = 'Train Dirty Document Field Detector Model'; '''
        ),
    ]
