# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-10 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_auto_20190319_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentnotificationsubscription',
            name='recipients_cc',
            field=models.CharField(blank=True, help_text='Semi-colon separated list of \n    emails to add as CC to each notification email.', max_length=1024, null=True),
        ),
    ]
