# Generated by Django 2.2.18 on 2021-08-02 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0014_webnotificationmessage_notification_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webnotificationmessage',
            name='redirect_link',
        ),
    ]
