# Generated by Django 2.2.18 on 2021-08-02 11:36

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0015_remove_webnotificationmessage_redirect_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='webnotificationmessage',
            name='redirect_link',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
