# Generated by Django 2.2.18 on 2021-08-05 12:38

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0016_webnotificationmessage_redirect_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webnotificationmessage',
            name='message',
        ),
        migrations.AddField(
            model_name='webnotificationmessage',
            name='message_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='webnotificationmessage',
            name='notification_type',
            field=models.CharField(blank=True, choices=[('DOCUMENT_ASSIGNED', 'document_assigned'), ('DOCUMENT_UNASSIGNED', 'document_unassigned'), ('CLAUSES_ASSIGNED', 'clauses_assigned'), ('CLAUSES_UNASSIGNED', 'clauses_unassigned'), ('DOCUMENTS_UPLOADED', 'documents_uploaded'), ('DOCUMENT_DELETED', 'document_deleted'), ('DOCUMENT_ADDED', 'document_added'), ('DOCUMENT_STATUS_CHANGED', 'document_status_updated'), ('CLUSTER_IMPORTED', 'cluster_imported'), ('FIELD_VALUE_DETECTION_COMPLETED', 'field_value_detection_completed'), ('CUSTOM_TERM_SET_SEARCH_FINISHED', 'custom_term_set_search_finished'), ('CUSTOM_COMPANY_TYPE_SEARCH_FINISHED', 'custom_company_type_search_finished'), ('DOCUMENT_SIMILARITY_SEARCH_FINISHED', 'document_similarity_search_finished'), ('TEXT_UNIT_SIMILARITY_SEARCH_FINISHED', 'text_unit_similarity_search_finished')], db_index=True, help_text='Notification type', max_length=100, null=True),
        ),
    ]
