# Generated by Django 2.2.20 on 2022-01-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0017_auto_20210805_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='webnotificationmessage',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
