# Generated by Django 2.2.20 on 2022-01-24 08:46

from django.db import migrations

from apps.notifications.models import WebNotificationTypes


def update_web_notification_messages(apps, schema_editor):
    WebNotificationMessage = apps.get_model('notifications', 'WebNotificationMessage')

    for i in WebNotificationMessage.objects.all():
        if i.notification_type and i.message_data:
            i.message = WebNotificationTypes.get_type_by_value(
                i.notification_type).message_template().format(**i.message_data)
            i.save(update_fields=['message'])


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0018_webnotificationmessage_message'),
    ]

    operations = [
        migrations.RunPython(update_web_notification_messages,
                             reverse_code=migrations.RunPython.noop),
    ]
