"""
    Contraxsuite API

    Contraxsuite API  # noqa: E501

    The version of the OpenAPI document: 2.3.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.document_set_annotator_coordinates_difference_request_first_letters_inner import DocumentSetAnnotatorCoordinatesDifferenceRequestFirstLettersInner


class TestDocumentSetAnnotatorCoordinatesDifferenceRequestFirstLettersInner(unittest.TestCase):
    """DocumentSetAnnotatorCoordinatesDifferenceRequestFirstLettersInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDocumentSetAnnotatorCoordinatesDifferenceRequestFirstLettersInner(self):
        """Test DocumentSetAnnotatorCoordinatesDifferenceRequestFirstLettersInner"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DocumentSetAnnotatorCoordinatesDifferenceRequestFirstLettersInner()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
