"""
    Contraxsuite API

    Contraxsuite API  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.task_queue_documents_data import TaskQueueDocumentsData


class TestTaskQueueDocumentsData(unittest.TestCase):
    """TaskQueueDocumentsData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTaskQueueDocumentsData(self):
        """Test TaskQueueDocumentsData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TaskQueueDocumentsData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
