"""
    Contraxsuite API

    Contraxsuite API  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.text_unit_cluster import TextUnitCluster


class TestTextUnitCluster(unittest.TestCase):
    """TextUnitCluster unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTextUnitCluster(self):
        """Test TextUnitCluster"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TextUnitCluster()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
