"""
    Contraxsuite API

    Contraxsuite API  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.document_field_category_create import DocumentFieldCategoryCreate


class TestDocumentFieldCategoryCreate(unittest.TestCase):
    """DocumentFieldCategoryCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDocumentFieldCategoryCreate(self):
        """Test DocumentFieldCategoryCreate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DocumentFieldCategoryCreate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
