"""
    Contraxsuite API

    Contraxsuite API  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.document_type_stats_data import DocumentTypeStatsData
globals()['DocumentTypeStatsData'] = DocumentTypeStatsData
from openapi_client.model.document_type_stats import DocumentTypeStats


class TestDocumentTypeStats(unittest.TestCase):
    """DocumentTypeStats unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDocumentTypeStats(self):
        """Test DocumentTypeStats"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DocumentTypeStats()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
