# coding: utf-8

"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.document_detail import DocumentDetail  # noqa: E501
from openapi_client.rest import ApiException

class TestDocumentDetail(unittest.TestCase):
    """DocumentDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test DocumentDetail
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.document_detail.DocumentDetail()  # noqa: E501
        if include_optional :
            return DocumentDetail(
                pk = 56, 
                name = '0', 
                document_type = '0', 
                file_size = 0, 
                folder = '0', 
                status = 56, 
                status_data = openapi_client.models.document_detail_status_data.DocumentDetail_status_data(
                    id = 56, 
                    name = '0', 
                    code = '0', 
                    order = 0, 
                    is_active = True, 
                    group = 56, ), 
                available_statuses_data = '0', 
                assignee = 56, 
                assign_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                assignee_data = openapi_client.models.document_detail_assignee_data.DocumentDetail_assignee_data(
                    pk = 56, 
                    first_name = '0', 
                    last_name = '0', 
                    username = 'a', 
                    role = 56, 
                    photo = '0', 
                    name = '0', ), 
                available_assignees_data = '0', 
                description = '0', 
                title = '0', 
                initial_annotation_id = '0', 
                page_locations = '0', 
                notes = [
                    openapi_client.models.document_detail_notes.DocumentDetail_notes(
                        pk = 56, 
                        note = '0', 
                        timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        user = openapi_client.models.document_detail_user.DocumentDetail_user(
                            pk = 56, 
                            first_name = '0', 
                            last_name = '0', 
                            username = 'a', 
                            role = 56, 
                            photo = '0', 
                            name = '0', ), 
                        location_start = -2147483648, 
                        location_end = -2147483648, 
                        document_id = 56, 
                        field_value_id = 56, 
                        field_id = '0', )
                    ], 
                field_values = '0', 
                field_value_objects = '0', 
                prev_id = '0', 
                next_id = '0', 
                sections = '0', 
                cluster_id = '0', 
                user_permissions = '0'
            )
        else :
            return DocumentDetail(
                status_data = openapi_client.models.document_detail_status_data.DocumentDetail_status_data(
                    id = 56, 
                    name = '0', 
                    code = '0', 
                    order = 0, 
                    is_active = True, 
                    group = 56, ),
                assignee_data = openapi_client.models.document_detail_assignee_data.DocumentDetail_assignee_data(
                    pk = 56, 
                    first_name = '0', 
                    last_name = '0', 
                    username = 'a', 
                    role = 56, 
                    photo = '0', 
                    name = '0', ),
                notes = [
                    openapi_client.models.document_detail_notes.DocumentDetail_notes(
                        pk = 56, 
                        note = '0', 
                        timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        user = openapi_client.models.document_detail_user.DocumentDetail_user(
                            pk = 56, 
                            first_name = '0', 
                            last_name = '0', 
                            username = 'a', 
                            role = 56, 
                            photo = '0', 
                            name = '0', ), 
                        location_start = -2147483648, 
                        location_end = -2147483648, 
                        document_id = 56, 
                        field_value_id = 56, 
                        field_id = '0', )
                    ],
        )

    def testDocumentDetail(self):
        """Test DocumentDetail"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
