"""
    Contraxsuite API

    Contraxsuite API  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.geo_alias_usage import GeoAliasUsage


class TestGeoAliasUsage(unittest.TestCase):
    """GeoAliasUsage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGeoAliasUsage(self):
        """Test GeoAliasUsage"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GeoAliasUsage()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
