# coding: utf-8

"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.clone_document_field_request import CloneDocumentFieldRequest  # noqa: E501
from openapi_client.rest import ApiException

class TestCloneDocumentFieldRequest(unittest.TestCase):
    """CloneDocumentFieldRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test CloneDocumentFieldRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.clone_document_field_request.CloneDocumentFieldRequest()  # noqa: E501
        if include_optional :
            return CloneDocumentFieldRequest(
                code = '0', 
                document_type = '0'
            )
        else :
            return CloneDocumentFieldRequest(
                code = '0',
                document_type = '0',
        )

    def testCloneDocumentFieldRequest(self):
        """Test CloneDocumentFieldRequest"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
