# Generated by Django 2.2.13 on 2021-04-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyze', '0027_create_transformer_db_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='similarityrun',
            name='distance_type',
            field=models.CharField(blank=True, choices=[('braycurtis', 'braycurtis'), ('canberra', 'canberra'), ('chebyshev', 'chebyshev'), ('cityblock', 'cityblock'), ('correlation', 'correlation'), ('cosine', 'cosine'), ('dice', 'dice'), ('euclidean', 'euclidean'), ('hamming', 'hamming'), ('jaccard', 'jaccard'), ('jensenshannon', 'jensenshannon'), ('kulsinski', 'kulsinski'), ('mahalanobis', 'mahalanobis'), ('minkowski', 'minkowski'), ('rogerstanimoto', 'rogerstanimoto'), ('russellrao', 'russellrao'), ('seuclidean', 'seuclidean'), ('sokalmichener', 'sokalmichener'), ('sokalsneath', 'sokalsneath'), ('sqeuclidean', 'sqeuclidean'), ('wminkowski', 'wminkowski'), ('yule', 'yule')], db_index=True, max_length=20, null=True),
        ),
    ]
