# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extract', '0004_auto_20170807_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoalias',
            name='alias',
            field=models.CharField(db_index=True, max_length=1024),
        ),
    ]
