# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-20 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extract', '0009_auto_20170920_1515'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currencyusage',
            options={'ordering': ('text_unit', 'usage_type', 'currency', '-amount')},
        ),
        migrations.AddField(
            model_name='currencyusage',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='currencyusage',
            name='amount_str',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
