# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-23 08:33
from __future__ import unicode_literals

from django.db import migrations


def migrate_durations(apps, schema_editor):
    DateDurationUsage = apps.get_model('extract', 'DateDurationUsage')
    for usage in DateDurationUsage.objects.all():
        usage.amount = usage.duration.days or usage.duration.seconds
        usage.duration_type = 'day' if usage.duration.days else 'second'
        usage.save()


class Migration(migrations.Migration):

    dependencies = [
        ('extract', '0019_auto_20170923_0833'),
    ]

    operations = [
        migrations.RunPython(migrate_durations),
    ]
