# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-24 08:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extract', '0026_auto_20170924_0824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='court',
            old_name='abbreviation',
            new_name='alias',
        ),
    ]
