# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-31 16:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extract', '0031_auto_20171031_1553'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='party',
            unique_together=set([('name', 'type_abbr')]),
        ),
    ]
