# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 12:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_auto_20170818_0632'),
        ('extract', '0034_auto_20171108_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('url', models.CharField(db_index=True, max_length=1000)),
                ('text_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.TextUnit')),
            ],
            options={
                'ordering': ('text_unit', '-count', 'url'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='urlusage',
            unique_together=set([('text_unit', 'url')]),
        ),
    ]
