# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-02-12 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extract', '0041_auto_20190209_1201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amountusage',
            options={'ordering': ('-amount',)},
        ),
        migrations.AlterModelOptions(
            name='citationusage',
            options={'ordering': ('-count',)},
        ),
        migrations.AlterModelOptions(
            name='copyrightusage',
            options={'ordering': ('-count',)},
        ),
        migrations.AlterModelOptions(
            name='courtusage',
            options={'ordering': ('-count',)},
        ),
        migrations.AlterModelOptions(
            name='currencyusage',
            options={'ordering': ('-amount',)},
        ),
        migrations.AlterModelOptions(
            name='datedurationusage',
            options={'ordering': ('amount',)},
        ),
        migrations.AlterModelOptions(
            name='dateusage',
            options={'ordering': ('-count',)},
        ),
        migrations.AlterModelOptions(
            name='definitionusage',
            options={'ordering': ('-count',)},
        ),
        migrations.AlterModelOptions(
            name='distanceusage',
            options={'ordering': ('-amount',)},
        ),
        migrations.AlterModelOptions(
            name='geoaliasusage',
            options={'ordering': ('-count',)},
        ),
        migrations.AlterModelOptions(
            name='geoentityusage',
            options={'ordering': ('-count',)},
        ),
        migrations.AlterModelOptions(
            name='partyusage',
            options={'ordering': ('-count',)},
        ),
        migrations.AlterModelOptions(
            name='percentusage',
            options={'ordering': ('-amount',)},
        ),
        migrations.AlterModelOptions(
            name='ratiousage',
            options={'ordering': ('-amount',)},
        ),
        migrations.AlterModelOptions(
            name='regulationusage',
            options={'ordering': ('-count',)},
        ),
        migrations.AlterModelOptions(
            name='termusage',
            options={'ordering': ['-count']},
        ),
        migrations.AlterModelOptions(
            name='trademarkusage',
            options={'ordering': ('-count',)},
        ),
        migrations.AlterModelOptions(
            name='urlusage',
            options={'ordering': ('-count',)},
        ),
        migrations.AlterField(
            model_name='amountusage',
            name='amount',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='amountusage',
            name='amount_str',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='amountusage',
            name='count',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='citationusage',
            name='citation_str',
            field=models.CharField(db_index=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='citationusage',
            name='count',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='citationusage',
            name='court',
            field=models.CharField(blank=True, db_index=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='citationusage',
            name='page',
            field=models.PositiveSmallIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='citationusage',
            name='page2',
            field=models.CharField(blank=True, db_index=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='citationusage',
            name='reporter',
            field=models.CharField(db_index=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='citationusage',
            name='reporter_full_name',
            field=models.CharField(blank=True, db_index=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='citationusage',
            name='volume',
            field=models.PositiveSmallIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='copyrightusage',
            name='count',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='court',
            name='alias',
            field=models.CharField(blank=True, db_index=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='courtusage',
            name='count',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='currencyusage',
            name='amount',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='currencyusage',
            name='amount_str',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='currencyusage',
            name='count',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='currencyusage',
            name='currency',
            field=models.CharField(db_index=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='currencyusage',
            name='usage_type',
            field=models.CharField(db_index=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='datedurationusage',
            name='amount',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='datedurationusage',
            name='amount_str',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='datedurationusage',
            name='count',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='datedurationusage',
            name='duration_days',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='datedurationusage',
            name='duration_type',
            field=models.CharField(blank=True, db_index=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='dateusage',
            name='count',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='dateusage',
            name='date_str',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='definitionusage',
            name='count',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='definitionusage',
            name='definition',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='distanceusage',
            name='amount',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='distanceusage',
            name='amount_str',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='distanceusage',
            name='count',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='distanceusage',
            name='distance_type',
            field=models.CharField(db_index=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='geoalias',
            name='type',
            field=models.CharField(db_index=True, default='abbreviation', max_length=1024),
        ),
        migrations.AlterField(
            model_name='geoaliasusage',
            name='count',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='geoentityusage',
            name='count',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='partyusage',
            name='count',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='percentusage',
            name='amount',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='percentusage',
            name='amount_str',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='percentusage',
            name='count',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='percentusage',
            name='total',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='percentusage',
            name='unit_type',
            field=models.CharField(db_index=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='ratiousage',
            name='amount',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='ratiousage',
            name='amount2',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='ratiousage',
            name='amount_str',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='ratiousage',
            name='count',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='ratiousage',
            name='total',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='regulationusage',
            name='count',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='term',
            name='source',
            field=models.CharField(db_index=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='termusage',
            name='count',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='trademarkusage',
            name='count',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='urlusage',
            name='count',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
