# Generated by Django 2.2.13 on 2020-07-13 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extract', '0057_blacklistrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklistrecord',
            name='entity_type',
            field=models.CharField(choices=[('party', 'party')], db_index=True, default='party', max_length=128),
        ),
    ]
