# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-13 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20180622_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewStatusGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('code', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('order', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['order', 'name', 'code'],
            },
        ),
    ]
