# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-12 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_auto_20180828_0418'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='app_label',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='action',
            name='model_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='action',
            name='object_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
