# Generated by Django 2.2.4 on 2019-09-12 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_auto_20190906_0727'),
    ]

    operations = [
        migrations.CreateModel(
            name='MethodStatsCollectorPlugin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(db_index=True, help_text='Full absolute path to a method like "apps.common.api.v1.AppVarsAPIView.get".', max_length=200, unique=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('log_sql', models.BooleanField(default=False)),
                ('callers_depth', models.PositiveSmallIntegerField(default=5)),
                ('batch_size', models.PositiveSmallIntegerField(default=100)),
                ('batch_time', models.PositiveSmallIntegerField(default=60)),
            ],
            options={
                'verbose_name_plural': 'Method Stats Collector Plug-in',
            },
        ),
    ]
