# Generated by Django 2.2.4 on 2019-11-01 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0022_threaddumprecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='threaddumprecord',
            name='cpu_usage_system_wide',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='threaddumprecord',
            name='memory_usage_system_wide',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
