# Generated by Django 2.2.13 on 2021-03-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0037_expire_appvars'),
    ]

    operations = [
        migrations.AddField(
            model_name='appvar',
            name='access_type',
            field=models.CharField(choices=[('all', 'Available for all users'), ('auth', 'Available for authenticated users '), ('admin', 'Available for superusers / admins only')], default='auth', max_length=10),
        ),
        migrations.AddField(
            model_name='historicalappvar',
            name='access_type',
            field=models.CharField(choices=[('all', 'Available for all users'), ('auth', 'Available for authenticated users '), ('admin', 'Available for superusers / admins only')], default='auth', max_length=10),
        ),
    ]
