# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-03 17:38
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentannotation',
            name='tag',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), size=None), blank=True, null=True, size=None),
        ),
    ]
