# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-19 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0006_documentfield_detection_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassifierDataSetEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, db_index=True, max_length=256, null=True)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ClassifierModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(blank=True, db_index=True, max_length=256, null=True)),
                ('document_class', models.CharField(blank=True, db_index=True, max_length=256, null=True)),
                ('trained_model', models.BinaryField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='documentfield',
            name='detection_model',
        ),
        migrations.AddField(
            model_name='classifiermodel',
            name='document_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fields.DocumentField'),
        ),
        migrations.AddField(
            model_name='classifierdatasetentry',
            name='field_detection_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fields.ClassifierModel'),
        ),
    ]
