# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-15 08:48
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('document', '0013_auto_20180213_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentFieldValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', django.contrib.postgres.fields.jsonb.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('location_start', models.PositiveSmallIntegerField()),
                ('location_end', models.PositiveSmallIntegerField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.Document')),
            ],
            options={
                'ordering': ('document_id', 'field__code'),
            },
        ),
        migrations.CreateModel(
            name='HistoricalDocumentFieldValue',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('value', django.contrib.postgres.fields.jsonb.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('location_start', models.PositiveSmallIntegerField()),
                ('location_end', models.PositiveSmallIntegerField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('document', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='document.Document')),
            ],
            options={
                'get_latest_by': 'history_date',
                'verbose_name': 'historical document field value',
                'ordering': ('-history_date', '-history_id'),
            },
        ),
        migrations.AlterField(
            model_name='documentfield',
            name='type',
            field=models.CharField(choices=[('float', 'float'), ('date', 'date'), ('duration', 'duration'), ('string', 'string'), ('company', 'company'), ('int', 'int'), ('related_info', 'related_info'), ('address', 'address')], db_index=True, default='string', max_length=30),
        ),
        migrations.AddField(
            model_name='historicaldocumentfieldvalue',
            name='field',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='document.DocumentField'),
        ),
        migrations.AddField(
            model_name='historicaldocumentfieldvalue',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentfieldvalue',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.DocumentField'),
        ),
    ]
