# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-07 06:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0024_auto_20180306_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='upload',
        ),
        migrations.RemoveField(
            model_name='historicaldocument',
            name='upload',
        ),
    ]
