# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-07 06:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20180307_0653'),
        ('document', '0025_auto_20180307_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.UploadSession'),
        ),
        migrations.AddField(
            model_name='historicaldocument',
            name='upload',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='project.UploadSession'),
        ),
    ]
