# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-08 11:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0027_auto_20180307_1345'),
        ('document', '0026_auto_20180308_0801'),
    ]

    operations = [
    ]
