# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-09 17:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0028_merge_20180308_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentfieldvalue',
            name='sentence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_field_values', to='document.TextUnit'),
        ),
        migrations.AddField(
            model_name='historicaldocumentfieldvalue',
            name='sentence',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='document.TextUnit'),
        ),
        migrations.AddField(
            model_name='textunit',
            name='location_end',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='textunit',
            name='location_start',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentfielddetector',
            name='extraction_hint',
            field=models.CharField(blank=True, choices=[('TAKE_FIRST', 'TAKE_FIRST'), ('TAKE_SECOND', 'TAKE_SECOND'), ('TAKE_LAST', 'TAKE_LAST')], db_index=True, default='TAKE_FIRST', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='documentfieldvalue',
            name='extraction_hint',
            field=models.CharField(blank=True, choices=[('TAKE_FIRST', 'TAKE_FIRST'), ('TAKE_SECOND', 'TAKE_SECOND'), ('TAKE_LAST', 'TAKE_LAST')], db_index=True, default='TAKE_FIRST', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldocumentfieldvalue',
            name='extraction_hint',
            field=models.CharField(blank=True, choices=[('TAKE_FIRST', 'TAKE_FIRST'), ('TAKE_SECOND', 'TAKE_SECOND'), ('TAKE_LAST', 'TAKE_LAST')], db_index=True, default='TAKE_FIRST', max_length=30, null=True),
        ),
    ]
