# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-02 07:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0056_auto_20180731_1435'),
        ('document', '0056_externalfieldvalue'),
    ]

    operations = [
    ]
