# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-25 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0075_auto_20180924_1728'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documenttypefieldcategory',
            options={'ordering': ('order', 'name'), 'verbose_name_plural': 'Document Type Field Categories'},
        ),
        migrations.AddField(
            model_name='documenttypefieldcategory',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
