# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-25 16:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0076_auto_20180925_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documenttypefieldcategory',
            name='type_fields',
        ),
        migrations.AddField(
            model_name='documenttypefield',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='document.DocumentTypeFieldCategory'),
        ),
    ]
