# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-03 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0082_auto_20181003_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentfield',
            name='code',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
