# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-03 20:32
from __future__ import unicode_literals

from django.db import migrations, models


def _migrate(apps, schema_editor):
    DocumentField = apps.get_model('document', 'DocumentField')
    for f in DocumentField.objects.all():  # type: DocumentField
        if f.formula:
            dependencies = f.depends_on_fields.all()
            for df in dependencies:
                try:
                    # trying to remove original calculated field from the dependencies of its dependencies
                    df.depends_on_fields.remove(f)
                except:
                    pass


class Migration(migrations.Migration):
    dependencies = [
        ('document', '0084_documenttype_editor_type'),
    ]

    operations = [
        migrations.RunPython(_migrate)
    ]
