# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-05 14:27
from __future__ import unicode_literals

import apps.common.fields
import django.core.serializers.json
from django.db import migrations
from apps.common.model_utils.improved_django_json_encoder import ImprovedDjangoJSONEncoder


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0085_clean_dependends_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='textunit',
            name='metadata',
            field=apps.common.fields.CustomJSONField(blank=True, encoder=ImprovedDjangoJSONEncoder, null=True),
        ),
    ]
