# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-12 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0091_auto_20181012_0827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentfieldvalue',
            old_name='sentence',
            new_name='text_unit',
        ),
        migrations.RenameField(
            model_name='externalfieldvalue',
            old_name='sentence_text',
            new_name='text_unit_text',
        ),
        migrations.RenameField(
            model_name='historicaldocumentfieldvalue',
            old_name='sentence',
            new_name='text_unit',
        ),
        migrations.RemoveField(
            model_name='classifiermodel',
            name='able_to_predict',
        ),
        migrations.RemoveField(
            model_name='classifiermodel',
            name='predicted_valid_values_number',
        ),
        migrations.RemoveField(
            model_name='classifiermodel',
            name='predicted_wrong_values_number',
        ),
        migrations.RemoveField(
            model_name='classifiermodel',
            name='test_sentences_number',
        ),
        migrations.RemoveField(
            model_name='classifiermodel',
            name='test_valid_fields_metric',
        ),
        migrations.RemoveField(
            model_name='classifiermodel',
            name='test_values_number',
        ),
        migrations.RemoveField(
            model_name='classifiermodel',
            name='test_wrong_fields_metric',
        ),
        migrations.RemoveField(
            model_name='classifiermodel',
            name='total_field_value_samples',
        ),
        migrations.RemoveField(
            model_name='classifiermodel',
            name='total_samples',
        ),
        migrations.AddField(
            model_name='classifiermodel',
            name='accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classifiermodel',
            name='test_documents_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classifiermodel',
            name='test_text_units_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classifiermodel',
            name='train_documents_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classifiermodel',
            name='train_text_units_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentfield',
            name='value_detection_strategy',
            field=models.CharField(choices=[('disabled', 'Field detection disabled'), ('use_regexps_only', 'No ML. Use regexp field detectors.'), ('use_formula_only', 'No ML. Use formula only.'), ('regexps_and_text_based_ml', 'Start with regexps, switch to text-based ML when possible.'), ('formula_and_fields_based_ml', 'Start with formula, switch to fields-based ML when possible.'), ('fields_based_ml_only', 'Use pre-trained field-based ML only.'), ('python_coded_field', 'Use python class for value detection.')], default='use_regexps_only', max_length=50),
        ),
    ]
