# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-19 11:34
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0130_auto_20190419_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentfield',
            name='unsure_choice_value',
            field=models.TextField(blank=True, help_text='Makes sense for machine learning \n    strategies with "Unsure" category. The strategy will return this value if probabilities of all other categories \n    appear lower than the specified threshold.', null=True),
        ),
        migrations.AddField(
            model_name='documentfield',
            name='value_detection_ml_confidence_threshold',
            field=models.FloatField(blank=True, default=0.9, help_text='Makes sense for machine learning \n    strategies with "Unsure" category. The strategy will return concrete result (one of choice values) only if \n    the probability of the detected value is greater than this threshold. Otherwise the strategy returns None \n    or the choice value specified in "Unsure choice value" field.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
