# Generated by Django 2.2 on 2019-05-31 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0140_auto_20190530_0845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='field_values',
        ),
        migrations.RemoveField(
            model_name='historicaldocument',
            name='field_values',
        ),
    ]
