# Generated by Django 2.2 on 2019-07-16 18:07

from django.db import migrations


def do_migrate(apps, schema_editor):
    DocumentFieldValue = apps.get_model('document', 'DocumentFieldValue')
    DocumentFieldValue.objects.filter(value='None|None').update(value=None)


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0142_auto_20190531_1437'),
    ]

    operations = [
        migrations.RunPython(do_migrate, reverse_code=migrations.RunPython.noop),
    ]
