# Generated by Django 2.2.4 on 2019-10-24 09:03

import apps.common.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0160_remove_docfieldval'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='fieldvalue',
            managers=[
                ('objects', apps.common.managers.BulkSignalsManager(use_in_migrations=True)),
            ],
        ),
        migrations.AlterField(
            model_name='textunit',
            name='text_hash',
            field=models.CharField(db_index=True, max_length=1024, null=True),
        ),
    ]
