# Generated by Django 2.2 on 2019-07-10 13:14

from django.db import migrations, connection
from apps.common.utils import dictfetchall


def do_migrate(apps, schema_editor):
    DocumentText = apps.get_model('document', 'DocumentText')
    DocumentMetadata = apps.get_model('document', 'DocumentMetadata')

    with connection.cursor() as cursor:
        cursor.execute('SELECT id as document_id, full_text FROM document_document')
        DocumentText.objects.bulk_create([DocumentText(**i) for i in dictfetchall(cursor)],
                                         ignore_conflicts=True)
    with connection.cursor() as cursor:
        cursor.execute('SELECT id as document_id, metadata FROM document_document')
        DocumentMetadata.objects.bulk_create([DocumentMetadata(**i) for i in dictfetchall(cursor)],
                                             ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0164_auto_20191107_0831'),
    ]

    operations = [
        migrations.RunPython(do_migrate, reverse_code=migrations.RunPython.noop),
    ]
