# Generated by Django 2.2.4 on 2019-12-06 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0169_documentfield_vectorizer_stop_words'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextUnitText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(null=True)),
                ('text_unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='document.TextUnit')),
            ],
        ),
    ]
