# Generated by Django 2.2.10 on 2020-03-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0186_auto_20200303_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentfieldmultilineregexdetector',
            name='extraction_hint',
            field=models.CharField(blank=True, choices=[('TAKE_FIRST', 'TAKE_FIRST'), ('TAKE_SECOND', 'TAKE_SECOND'), ('TAKE_LAST', 'TAKE_LAST'), ('TAKE_MIN', 'TAKE_MIN'), ('TAKE_MAX', 'TAKE_MAX')], db_index=True, default='TAKE_FIRST', help_text='Provide additional instruction on which \n    specific values should be prioritized for extraction, when multiple values of the same type \n    (e.g., Company, Person, Geography) are found within the relevant detected Text Unit.', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='documentfieldmultilineregexdetector',
            name='regexps_pre_process_lower',
            field=models.BooleanField(default=True, help_text='Convert a sentence or a paragraph’s characters to \n    lowercase prior to running regular expressions for field detection.'),
        ),
        migrations.AddField(
            model_name='documentfieldmultilineregexdetector',
            name='text_part',
            field=models.CharField(choices=[('FULL', 'Whole text'), ('BEFORE_REGEXP', 'Before matching substring'), ('AFTER_REGEXP', 'After matching substring'), ('INSIDE_REGEXP', 'Inside matching substring')], db_index=True, default='FULL', help_text='Defines which part of the matched Text Unit \n    should be passed to the extraction function. Example: In the string "2019-01-23 is the start date and 2019-01-24 is the \n    end date," if text part = "Before matching substring" and Include regexp is "is.{0,100}start" then "2019-01-23" will be \n    parsed correctly as the start date.', max_length=30),
        ),
    ]
