# Generated by Django 2.2.10 on 2020-03-23 15:51

from django.db import migrations, connection


# Code moved to 0188 for performance increasing

class Migration(migrations.Migration):
    dependencies = [
        ('document', '0188_auto_20200323_1551'),
    ]

    operations = [
    ]
