# Generated by Django 2.2.13 on 2020-06-29 07:43

import apps.document.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0203_auto_20200617_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentfield',
            name='display_yes_no',
            field=models.BooleanField(default=False, help_text='Checking this box will display “Yes” if Related Info text is found, and display “No” if no text is found.'),
        ),
    ]
