# Generated by Django 2.2.13 on 2020-08-05 16:22
import datetime

from django.db import migrations, models, connection, transaction
import django.db.models.deletion
import picklefield.fields

from apps.common.sql_commons import dropping_constraints_and_indexes, maintenance_work_mem


class TextUnitProjectModifier:
    TABLE_NAME = 'document_textunit'
    DOC_TABLE_NAME = 'document_document'

    def __init__(self,
                 schema_name: str = 'public'):
        self.schema_name = schema_name

    def update_text_units(self):
        with transaction.atomic():
            with connection.cursor() as cursor:
                with dropping_constraints_and_indexes(
                        cursor, self.TABLE_NAME, logger_proc=lambda s: print(s)):
                    with maintenance_work_mem(cursor, logger_proc=lambda s: print(s)):
                        cursor.execute(f'''UPDATE {self.TABLE_NAME} AS t SET project_id = d.project_id
                                        FROM {self.DOC_TABLE_NAME} AS d WHERE t.document_id = d.id;''')


def add_project_field(_apps, _schema_editor):
    m = TextUnitProjectModifier()
    start = datetime.datetime.now()
    m.update_text_units()
    time_taken = (datetime.datetime.now() - start).total_seconds()
    print(f'Migration took {time_taken}s.')


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0042_auto_20200713_1518'),
        ('document', '0207_auto_20200718_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='textunit',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Project'),
        ),
        migrations.AlterField(
            model_name='documentfield',
            name='detect_limit_unit',
            field=models.CharField(choices=[('NONE', 'No Limit'), ('UNIT', 'Limit to N "text unit type" units')],
                                   default='NONE', help_text='Choose to add an upward limit to the amount of document text \n                                         ContraxSuite will search for this Document Field. For example, you can choose \n                                         to only search the first 10 paragraphs of text for the value required (this \n                                         often works best for values like “Company,” “Execution Date,” or “Parties,”\n                                         all of which typically appear in the first few paragraphs of a contract).', max_length=10),
        ),
        migrations.AlterField(
            model_name='documenttable',
            name='table',
            field=picklefield.fields.PickledObjectField(compress=True, editable=False),
        ),
        migrations.RunPython(
            add_project_field, reverse_code=migrations.RunPython.noop
        )
    ]
