# Generated by Django 2.2.13 on 2020-08-18 10:11

from django.conf import settings
from django.db import migrations, models, connection
import django.db.models.deletion


def add_user_field(_apps, _schema_editor):
    # return
    with connection.cursor() as cursor:
        add_user_ref(cursor, 'document_documentnote',
                     'document_historicaldocumentnote')
        add_user_ref(cursor, 'document_textunitnote',
                     'document_historicaltextunitnote')


def add_user_ref(cursor, note_table: str, history_table: str):
        cursor.execute(f'''
            UPDATE {history_table}
            SET user_id = history_user_id;''')
        cursor.execute(f'''
            UPDATE {history_table} AS hn
            SET username = usr.username
            FROM users_user AS usr
            WHERE usr.id = hn.history_user_id;''')

        cursor.execute(f'''
            UPDATE {note_table} AS dn
            SET user_id = hn.history_user_id, username = hn.username
            FROM {history_table} AS hn
            WHERE dn.id = hn.id;''')
        cursor.execute(f'''
            UPDATE {note_table} AS dn
            SET user_id = (select id from users_user order by id limit(1)),
                username = (select username from users_user order by id limit(1))
            WHERE dn.user_id is null;''')


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('document', '0209_auto_20200818_1011'),
    ]

    operations = [
        migrations.RunPython(
            add_user_field, reverse_code=migrations.RunPython.noop
        )
    ]
