# Generated by Django 2.2.13 on 2020-09-14 14:49

import apps.common.models
import apps.document.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0214_auto_20200910_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='ocr_grade',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaldocument',
            name='ocr_grade',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentfielddetector',
            name='regexps_pre_process_lower',
            field=models.BooleanField(default=True, help_text="Set 'ignore case' flag for both 'Include regexps' and 'Exclude regexps' options.", verbose_name='Make search case-insensitive'),
        ),
        migrations.AlterField(
            model_name='documentfieldmultilineregexdetector',
            name='regexps_pre_process_lower',
            field=models.BooleanField(default=True, help_text="Set 'ignore case' flag for both 'Include regexps' and 'Exclude regexps' options.", verbose_name='Make search case-insensitive'),
        ),
        migrations.AlterField(
            model_name='historicaldocument',
            name='status',
            field=models.ForeignKey(blank=True, db_constraint=False, default=apps.common.models.get_default_status, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='common.ReviewStatus'),
        ),
        migrations.AlterField(
            model_name='historicaldocumentnote',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalfieldannotation',
            name='status',
            field=models.ForeignKey(blank=True, db_constraint=False, default=apps.document.models.FieldAnnotationStatus.initial_status_pk, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='document.FieldAnnotationStatus'),
        ),
        migrations.AlterField(
            model_name='historicaltextunitnote',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
