# Generated by Django 2.2.10 on 2020-11-17 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0218_auto_20201118_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentfield',
            name='choices',
            field=models.TextField(blank=True, help_text='Newline-separated choices. A choice cannot contain a comma.', null=True),
        ),
        migrations.AlterField(
            model_name='documentfield',
            name='type',
            field=models.CharField(db_index=True, default='string', max_length=30),
        ),
    ]
