# Generated by Django 2.2.13 on 2020-10-30 08:22

import apps.document.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('document', '0217_auto_20201111_2137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ('name',), 'permissions': (('change_document_field_values', 'Change document field values'), ('change_status', 'Change document status'))},
        ),
        migrations.AlterModelOptions(
            name='documentfield',
            options={'ordering': ('long_code',), 'permissions': (('view_documentfield_stats', 'View document field stats'), ('clone_documentfield', 'Clone document field'), ('import_documentfield', 'Import document field'), ('export_documentfield', 'Export document field'))},
        ),
        migrations.AlterModelOptions(
            name='documenttype',
            options={'ordering': ('code', 'modified_by', 'modified_date'), 'permissions': (('view_documenttype_stats', 'View document type stats'), ('clone_documenttype', 'Clone document type'), ('import_documenttype', 'Import document type'), ('export_documenttype', 'Export document type'))},
        ),
        migrations.AlterModelManagers(
            name='document',
            managers=[
                ('objects', apps.document.models.DocumentObjectsManager()),
            ],
        ),
        migrations.AddField(
            model_name='documenttype',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='document_type_managers', to=settings.AUTH_USER_MODEL),
        ),
    ]
