# Generated by Django 2.2.13 on 2021-02-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0231_move_detecting_limits'),
    ]

    operations = [
        migrations.RunSQL('''DELETE FROM document_documentpdfrepresentation;'''),
        migrations.AlterField(
            model_name='documentfielddetector',
            name='detect_limit_count',
            field=models.IntegerField(db_index=True, default=0,
                                      help_text='Specify the maximum \n    range for a bounded search. Field detection begins at the top of the document and continues until this Nth \n    "Detect limit unit" element.'),
        ),
        migrations.AlterField(
            model_name='documentfielddetector',
            name='detect_limit_unit',
            field=models.CharField(choices=[('NONE', 'No Limit'), ('UNIT', 'Limit to N "text unit type" units')], default='NONE',
                                   help_text='Choose to add an upward limit to the amount of document text \n                                             ContraxSuite will search for this Document Field. For example, you can choose \n                                             to only search the first 10 paragraphs of text for the value required (this \n                                             often works best for values like “Company,” “Execution Date,” or “Parties,”\n                                             all of which typically appear in the first few paragraphs of a contract).', max_length=10),
        ),

        migrations.RemoveField(
            model_name='documentpdfrepresentation',
            name='char_bboxes',
        ),
        migrations.RemoveField(
            model_name='documentpdfrepresentation',
            name='pages',
        ),
        migrations.AddField(
            model_name='documentpdfrepresentation',
            name='char_bboxes',
            field=models.BinaryField(blank=True,
                                     help_text='Bounding boxes of all characters of the document text in \n                                           format of list of [page_num, x_on_page, y_on_page, w, h].', null=True),
        ),
        migrations.AddField(
            model_name='documentpdfrepresentation',
            name='pages',
            field=models.BinaryField(blank=True,
                                     help_text='Information on PDF representation of the document pages.\n        List of dictionaries: { \'number\': ..., \'start\': ..., \'end\': ..., \'bbox\': ... }\n        where\n        "start" is offset in plain text of the first character on the page;\n        "end" is offset in plain text + 1 of the last character on the page;\n        "bbox" is bounding box in PDF coordinates in format: [x, y, w, h]. X and Y are usually zeros.', null=True),
        ),
    ]
