# Generated by Django 2.2.18 on 2021-04-19 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0239_auto_20210402_1120'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='documentfield',
            name='document_do_python__89da0f_idx',
        ),
        migrations.RemoveField(
            model_name='documentfield',
            name='python_coded_field',
        ),
    ]
