# Generated by Django 2.2.18 on 2021-04-23 08:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0240_auto_20210419_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttable',
            name='bounding_rect',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='documenttable',
            name='page',
            field=models.FloatField(null=False, default=0, db_index=True),
        ),
    ]
