/*
 * Contraxsuite API
 * Contraxsuite API
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for DateDurationUsage
 */
public class DateDurationUsageTest {
    private final DateDurationUsage model = new DateDurationUsage();

    /**
     * Model tests for DateDurationUsage
     */
    @Test
    public void testDateDurationUsage() {
        // TODO: test DateDurationUsage
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'amountStr'
     */
    @Test
    public void amountStrTest() {
        // TODO: test amountStr
    }

    /**
     * Test the property 'durationType'
     */
    @Test
    public void durationTypeTest() {
        // TODO: test durationType
    }

    /**
     * Test the property 'durationDays'
     */
    @Test
    public void durationDaysTest() {
        // TODO: test durationDays
    }

    /**
     * Test the property 'count'
     */
    @Test
    public void countTest() {
        // TODO: test count
    }

    /**
     * Test the property 'pk'
     */
    @Test
    public void pkTest() {
        // TODO: test pk
    }

    /**
     * Test the property 'textUnitPk'
     */
    @Test
    public void textUnitPkTest() {
        // TODO: test textUnitPk
    }

    /**
     * Test the property 'textUnitUnitType'
     */
    @Test
    public void textUnitUnitTypeTest() {
        // TODO: test textUnitUnitType
    }

    /**
     * Test the property 'textUnitLocationStart'
     */
    @Test
    public void textUnitLocationStartTest() {
        // TODO: test textUnitLocationStart
    }

    /**
     * Test the property 'textUnitLocationEnd'
     */
    @Test
    public void textUnitLocationEndTest() {
        // TODO: test textUnitLocationEnd
    }

    /**
     * Test the property 'textUnitDocumentPk'
     */
    @Test
    public void textUnitDocumentPkTest() {
        // TODO: test textUnitDocumentPk
    }

    /**
     * Test the property 'textUnitDocumentName'
     */
    @Test
    public void textUnitDocumentNameTest() {
        // TODO: test textUnitDocumentName
    }

    /**
     * Test the property 'textUnitDocumentDescription'
     */
    @Test
    public void textUnitDocumentDescriptionTest() {
        // TODO: test textUnitDocumentDescription
    }

    /**
     * Test the property 'textUnitDocumentDocumentType'
     */
    @Test
    public void textUnitDocumentDocumentTypeTest() {
        // TODO: test textUnitDocumentDocumentType
    }

}
