/*
 * Contraxsuite API
 * Contraxsuite API
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for MLModel
 */
public class MLModelTest {
    private final MLModel model = new MLModel();

    /**
     * Model tests for MLModel
     */
    @Test
    public void testMLModel() {
        // TODO: test MLModel
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'version'
     */
    @Test
    public void versionTest() {
        // TODO: test version
    }

    /**
     * Test the property 'vectorName'
     */
    @Test
    public void vectorNameTest() {
        // TODO: test vectorName
    }

    /**
     * Test the property 'modelPath'
     */
    @Test
    public void modelPathTest() {
        // TODO: test modelPath
    }

    /**
     * Test the property 'isActive'
     */
    @Test
    public void isActiveTest() {
        // TODO: test isActive
    }

    /**
     * Test the property '_default'
     */
    @Test
    public void _defaultTest() {
        // TODO: test _default
    }

    /**
     * Test the property 'applyTo'
     */
    @Test
    public void applyToTest() {
        // TODO: test applyTo
    }

    /**
     * Test the property 'targetEntity'
     */
    @Test
    public void targetEntityTest() {
        // TODO: test targetEntity
    }

    /**
     * Test the property 'language'
     */
    @Test
    public void languageTest() {
        // TODO: test language
    }

    /**
     * Test the property 'textUnitType'
     */
    @Test
    public void textUnitTypeTest() {
        // TODO: test textUnitType
    }

    /**
     * Test the property 'project'
     */
    @Test
    public void projectTest() {
        // TODO: test project
    }

}
