/*
 * Contraxsuite API
 * Contraxsuite API
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.ProjectDocumentSimilarityResponseData;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ProjectDocumentSimilarityResponse
 */
public class ProjectDocumentSimilarityResponseTest {
    private final ProjectDocumentSimilarityResponse model = new ProjectDocumentSimilarityResponse();

    /**
     * Model tests for ProjectDocumentSimilarityResponse
     */
    @Test
    public void testProjectDocumentSimilarityResponse() {
        // TODO: test ProjectDocumentSimilarityResponse
    }

    /**
     * Test the property 'data'
     */
    @Test
    public void dataTest() {
        // TODO: test data
    }

    /**
     * Test the property 'documentAId'
     */
    @Test
    public void documentAIdTest() {
        // TODO: test documentAId
    }

    /**
     * Test the property 'documentAName'
     */
    @Test
    public void documentANameTest() {
        // TODO: test documentAName
    }

    /**
     * Test the property 'totalRecords'
     */
    @Test
    public void totalRecordsTest() {
        // TODO: test totalRecords
    }

}
