
#contrax-ingress

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.domain_name }}-crt
spec:
  secretName: {{ .Values.domain_name }}-crt
  dnsNames:
  - {{ .Values.domain_name }}
  # acme:
  #   config:
  #   - http01:
  #       ingressClass: nginx
  #     domains:
  #     - {{ .Values.domain_name }}
  issuerRef:
    name: {{ .Values.domain_name }}-issuer
    kind: Issuer