#contrax-ingress

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: contrax-ingress
  namespace: {{ .Values.namespace | quote }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "{{ .Values.domainName }}-issuer"
    nginx.ingress.kubernetes.io/proxy-body-size: 5120M
spec:
  tls:
  - hosts:
    - {{ .Values.domainName }}
    secretName: "{{ .Values.domainName }}-key"
  rules:
  - host: {{ .Values.domainName }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: contrax-nginx  
            port: 
              number: 8080

---

#contrax-ingress-basic-auth

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: contrax-ingress-auth
  namespace: {{ .Values.namespace | quote }}
  annotations:
    ingress.kubernetes.io/rewrite-target: /mlflow
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "{{ .Values.domainName }}-issuer"
    nginx.ingress.kubernetes.io/proxy-body-size: 5120M
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
spec:
  tls:
  - hosts:
    - {{ .Values.domainName }}
    secretName: "{{ .Values.domainName }}-key"
  rules:
  - host: {{ .Values.domainName }}
    http:
      paths:
      - path: /jupyter
        pathType: Prefix
        backend:
          service: 
            name: contrax-jupyter
            port:
              number: 8888
      - path: /kibana
        pathType: Prefix
        backend:
          service:
            name: contrax-kibana
            port:
              number: 5601
      - path: /contraxmlflowartifacts
        pathType: Prefix
        backend:
          service:
            name: contrax-minio
            port:
              number: 9000
      - path: /mlflow
        pathType: Prefix
        backend:
          service:
            name: contrax-mlflow-tracking
            port: 
              number: 5000
      - path: /flower
        pathType: Prefix
        backend:
          service:
            name: contrax-flower
            port: 
              number: 5555
---
#contrax-ingress-monitoring

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: contrax-ingress
  namespace: monitoring
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "{{ .Values.domainName }}-issuer"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  tls:
  - hosts:
    - {{ .Values.domainName }}
    secretName: "{{ .Values.domainName }}-key"
  rules:
  - host: {{ .Values.domainName }}
    http:
      paths:
      - path: /grafana/?(.*)
        pathType: Prefix
        backend:
          service:
            name: monitoring-grafana
            port:
              number: 80

---
#contrax-ingress-monitoring

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: contrax-ingress-rook-ceph
  namespace: rook-ceph
  annotations:
    kubernetes.io/ingress.class: "nginx"
    #kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: "{{ .Values.domainName }}-issuer"
    ingress.kubernetes.io/rewrite-target: /ceph-dashboard
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/server-snippet: |
      proxy_ssl_verify off;
spec:
  tls:
  - hosts:
    - {{ .Values.domainName }}
    secretName: "{{ .Values.domainName }}-key"
  rules:
  - host: {{ .Values.domainName }}
    http:
      paths:
      - path: /ceph-dashboard
        pathType: Prefix
        backend:
          service:
            name: rook-ceph-mgr-dashboard
            port:
              number: 8443