apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: {{ .Values.domain_name }}-issuer
  namespace: {{ .Values.namespace }}
spec:
  acme:
    {{ if and .Values.letsencryptenv (eq .Values.letsencryptenv "prod") }}
    server: https://acme-v02.api.letsencrypt.org/directory
    {{ else }}
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    {{ end }}
    email: support@lexpredict.com
    privateKeySecretRef:
      name: {{ .Values.domain_name }}-key
    solvers:
    - http01:
        ingress:
          class:  nginx
