apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: "{{ .Values.domainName }}-issuer"
  namespace: {{ .Values.namespace | quote }}
spec:
  acme:
    {{ if and .Values.letsencryptenv (eq .Values.letsencryptenv "prod") }}
    server: https://acme-v02.api.letsencrypt.org/directory
    {{ else }}
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    {{ end }}
    email: support@lexpredict.com
    privateKeySecretRef:
      name: {{ .Values.domainName }}-key
    solvers:
    - http01:
        ingress:
          class:  nginx
