---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Values.namespace | quote }}
  name: backup
spec:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Values.namespace | quote }}
  name: contrax-celery-beat
spec:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Values.namespace | quote }}
  name: celery-worker-state
spec:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Values.namespace | quote }}
  name: contrax-powa-web
spec:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200M

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Values.namespace | quote }}
  name: contraxsuite-additional-fixtures
spec:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Values.namespace | quote }}
  name: contraxsuite-data-media
spec:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Values.namespace | quote }}
  name: contraxsuite-tes-data-media
spec:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Values.namespace | quote }}
  name: contraxsuite-data-update
spec:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Values.namespace | quote }}
  name: contraxsuite-jupyter-add-req
spec:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Values.namespace | quote }}
  name: contraxsuite-minio
spec:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Values.namespace | quote }}
  name: contraxsuite-mlflow-tracking
spec:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Values.namespace | quote }}
  name: contraxsuite-nginx-conf
spec:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Values.namespace | quote }}
  name: contraxsuite-nginx-certs
spec:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200M

# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   namespace: {{ .Values.namespace | quote }}
#   name: contraxsuite-frontend-nginx-volume
# spec:
#   storageClassName: ceph-block
  
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Values.namespace | quote }}
  name: contraxsuite-frontend
spec:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200M

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Values.namespace | quote }}
  name: contraxsuite-nginx-server-include
spec:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200M

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Values.namespace | quote }}
  name: contraxsuite-notebooks
spec:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Values.namespace | quote }}
  name: contraxsuite-ssl-certs
spec:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200M

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Values.namespace | quote }}
  name: contraxsuite-third-party-dependencies
spec:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Values.namespace | quote }}
  name: elastalert-rules
spec:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200M

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Values.namespace | quote }}
  name: elasticsearch-data
spec:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Values.namespace | quote }}
  name: elastalert-rule-templates
spec:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100M

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Values.namespace | quote }}
  name: filebeat-data
spec:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi


---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Values.namespace | quote }}
  name: metricbeat-data
spec:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Values.namespace | quote }}
  name: postgres-data-11
spec:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Values.namespace | quote }}
  name: rabbitmq-data
spec:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Values.namespace | quote }}
  name: redis-data
spec:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
